services:
  mogakgo-db:
    image: mysql:8.2.0
    container_name: mogakgo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root!
      MYSQL_DATABASE: mogakgo
    ports:
      - "3306:3306"
  mogakgo-redis:
    image: redis:latest
    container_name: mogakgo-redis
    ports:
      - "6379:6379"
  mogakgo-mongodb:
    image: mongo:latest
    container_name: mogakgo-mongodb
    environment:
      MONGI_INIT_DATABSE: mogakgo
    ports:
      - "27017:27017"